# 导入RT-Thread的自定义构建函数，几乎每一个RT-Thread的Sconscript都需要这么做。
# 只有导入了building模块，才可以使用2.2.2介绍的RT-Thread自定义Scons函数
from building import * 

cwd     = GetCurrentDir() # 获取当前脚本的路径
CPPPATH = [cwd] # 将当前路径加入构建搜索的头文件路径
src     = Split('''
bsp.c
src/bsp_led.c
src/bsp_fmc_io.c
''')

# add include path.
path  = [cwd + '/inc',cwd]

# 使用DefineGroup创建一个名为BSP的组
# 该Group是否被添加到工程中，参与编译，取决于depend的宏是否在Kconfig中被使能。
# 即上述的头文件路径和C文件是否被编译，取决于用户在Kconfig中是否使能了RT_USING_FINSH
group = DefineGroup('BSP', src,depend = [''],CPPPATH = path) 

Return('group') # 将当前脚本指定的构建对象返回上级SCons脚本
